### PR TITLE
Support Django 5.0

### PR DESCRIPTION
**Pull request by ashwanthbalakrishnan5**
#370 Added Support for Django 5.0

### CODE REVIEW

**Comment by ashwanthbalakrishnan5** [comment]
@suavesav any updates ?

**Comment by VBobCat** [comment]
What's hindering this release?

**Comment by ashwanthbalakrishnan5** [comment]
> What's hindering this release?

This repo is inactive and not maintained

**Comment by ashwanthbalakrishnan5** [comment]
Closing this as the Repo not actively maintained

**Pull request closed without merging**
