### PR TITLE
add Python 3.6, Django 2.1, DRF 3.8

### PR DESCRIPTION
**Pull request by ryochiji**
Mostly a straight port of https://github.com/AltSchool/dynamic-rest/pull/237/ mostly to run through Circle.

### CODE REVIEW

**Comment by jgissend10** [comment]
I pulled this into my 3.8 project and it breaks.


#246 Outlines the issue I'm having. drf has removed the following function that this project imports. I've confirmed things work if this function is placed in the file instead of using the import.

`
def replace_methodname(format_string, methodname):
    """
    Partially format a format_string, swapping out any
    '{methodname}' or '{methodnamehyphen}' components.
    """
    methodnamehyphen = methodname.replace('_', '-')
    ret = format_string
    ret = ret.replace('{methodname}', methodname)
    ret = ret.replace('{methodnamehyphen}', methodnamehyphen)
    return ret
`

**Comment by starsep** [comment]
Any updates?
I would appreciate Django 2.1 support
Thanks and good luck!

**Comment by jnaous** [comment]
Hiya guys! LMK if I can help get this merged. I really need 2.1 support!

**Comment by threewordphrase** [comment]
Me as well, I would like to use this library but need Python 3.6 / Django 2.1 support. Let me know if I can help get this merged in!

**Comment by wroscoe** [comment]
@threewordphrase Looks like the maintainer no longer works for altschool so this PR should be moved to this fork... https://github.com/asaak-co/dynamic-rest

**Comment by joshvillbrandt** [comment]
+1 for the merge since there is a security issue on older versions of DRF

https://github.com/AltSchool/dynamic-rest/issues/246#issuecomment-495399046

**Comment by jgissend10** [comment]
See this PR https://github.com/AltSchool/dynamic-rest/pull/276

> We should also add support for DRF 3.9.1 since Github has started reporting a vulnerability on older versions of DRF.
> 
> > [WS-2019-0037](https://github.com/encode/django-rest-framework/commit/75a489150ae24c2f3c794104a8e98fa43e2c9ce9) (moderate severity)
> > Vulnerable versions: < 3.9.1
> > Patched version: 3.9.1
> > Django-Rest-Framework, before 3.9.1, has a XSS vulnerability caused by disabled autoescaping in the default DRF Browsable API view templates.
> 
> [#246 (comment)](https://github.com/AltSchool/dynamic-rest/issues/246#issuecomment-495399046)

**Comment by simkimsia** [comment]
Please close this since this is fixed in master

**Comment by neilfrndes** [comment]
> @threewordphrase Looks like the maintainer no longer works for altschool so this PR should be moved to this fork... https://github.com/asaak-co/dynamic-rest

I find dynamic rest very useful, but have hit a roadblock because of incompatible versions: Py3.8 + Django3 + DRF 3.10

I'm curious to know if 
1) the asaak-co repo is the 'officialy' maintained repository?
2) is Django3 support is planned ?

Thank you for this helpful project!

**Pull request closed without merging**
