### PR TITLE
add py36 and drf38 to test, update test requirements

### PR DESCRIPTION
**Pull request by daddz**
* add python 3.6 to circle.yml
* update requirements for djangorestframework to <3.9
* update test requirements
* add py36-django20-drf38 to tox tests
* add django 2.1 to tests

### CODE REVIEW

**Comment by ryochiji** [comment]
@daddz - Thanks for doing this. Happy to merge if you could rebase to resolve the conflict.

**Comment by t3rm5** [comment]
+1 for DRF 3.8.2 support

**Comment by pista329** [comment]
@daddz @ryochiji @auvipy guys it would be awesome if this gets merged. Great work!. Have been waiting for dj2.1 support

**Comment by jgissend10** [comment]
+1 For this. Currently using 2.1 and 3.8.2 and would love to get this integrated into my project.

**Comment by ryochiji** [comment]
Thanks for the PR and the comments. I've ported this PR over to #254 (to resolve the conflict but also because PRs from forks don't go through Circle) so I'm closing this PR and will work on getting the other one out soon.

**Pull request closed without merging**
