### PR TITLE
Py{35-36} drf{38-39}, Django{20-21}

### PR DESCRIPTION
**Pull request by imposeren**
Includes commits by @jgissend10 and @ryochiji .

* Combined #259, #254.
* Added new version combinations to the tox environs matrix.
* fixed failed tests (to run tests locally: `tox -e py36-django20-drf38,py36-django20-drf39,py36-django21-drf38,py36-django21-drf39 `)

### CODE REVIEW

**Comment by imposeren** [comment]
@asaak-co or @aleontiev can anybody of you merge and publish new version on PyPI?

**Comment by stardust85** [comment]
@imposeren thanks for the effort around this. Also looking forward to see this merged!

**Comment by cescobarf** [comment]
I think this fix is also compatible with Django 2.2, since I've been using it with no problems

**Comment by stardust85** [comment]
Django 2.0 reached its end of life according to https://www.djangoproject.com/weblog/2015/jun/25/roadmap/, so we can remove it.

**Comment by jgissend10** [comment]
@imposeren https://github.com/AltSchool/dynamic-rest/pull/254#issuecomment-484703271

**Comment by simkimsia** [comment]
@cescobarf how do you use this PR for Django 2.2 given that there's no git version released for it?

@jgissend10 Is it even possible for @imposeren to send the PR to this fork https://github.com/asaak-co/dynamic-rest?

**Comment by imposeren** [comment]
@simkimsia aleontiev/dynamic-rest@master seems to be bit out of date: when I try to create a PR I get a lot of other commits introduced (150 commits with oldest being dated 2017-12-05). I might cherry-pick my changes and try to create a PR for that other repo, but it looks like that other repo misses a lot of other "fixes".

**Comment by ryochiji** [comment]
For everyone following this PR, the changes in this PR have now been released on PyPI as v1.9.4.

**Pull request merged**
