### PR TITLE
Upgraded django debug toolbar to include a fix

### PR DESCRIPTION
**Pull request by shanx**
Upgraded django debug toolbar to include fix described here: https://github.com/jazzband/django-debug-toolbar/issues/856

### CODE REVIEW

**Comment by auvipy** [comment]
try to pass the circle ci build

**Comment by shanx** [comment]
The test failure is due to debug toolbar version 1.5 not supporting django 1.7 anymore. What is the stance of dynamic rest about supporting django 1.7?

**Comment by auvipy** [comment]
1.7 should be dropped as it's no longer maintained.

**Comment by shanx** [comment]
Closing, this has been fixed in 512a5c4cc833f174e4ffc39ec39fdf59e974a03a

**Pull request closed without merging**
