### PR TITLE
Deprecated django 1.7

### PR DESCRIPTION
**Pull request by shanx**
Deprecated the use of django 1.7 as per discussion here: #129. And only now do I find out that auvipy is not a developer of the project :)

### CODE REVIEW

**Comment by aleontiev** [comment]
@shanx we would like to continue supporting 1.7 until we are able to transition away from 1.7 internally. Our upgrade to 1.10 is almost complete; should be good to merge this in a week or two. The changes are small, so I don't foresee any significant conflicts happening in that time.

**Comment by shanx** [comment]
@aleontiev thanks for you feedback! Is there a way to talk to you guys directly, maybe through irc or something? We are going to make heavy use of dynamic-rest in a system that we are developing and hope to gift back to this wonderful project you guys have started. So would be nice to discuss things.

**Comment by aleontiev** [comment]
@shanx thats great to hear! I created a glitter for the project here: https://gitter.im/dynamic-rest, we can chat there

**Comment by aleontiev** [comment]
Officially dropped support for 1.7

**Pull request closed without merging**
