### PR TITLE
Compatibility with Django 3

### PR DESCRIPTION
**Pull request by amandeep-r**
I went through and replaced `from django.utils import six` with `import six` I think There still needs to be some polishing up done in the requirements files etc.

### CODE REVIEW

**Comment by OmenApps** [comment]
Django 3 was released nearly a year ago. This was PR passed all checks, was approved in July, and marked ready in October. It's now November. Is something still pending?

**Comment by aleontiev** [comment]
:+1: thank you @amandeep-r and @OmenApps for the reminder :)

**Comment by rsplaul** [comment]
Is there a timeline for a release version with Django 3 support?

**Comment by mdylanbell** [comment]
Another request to release this along with [3.2 support](https://github.com/AltSchool/dynamic-rest/pull/318).

**Pull request merged**
